-- Extensión de cotizaciones para el flujo de proformas.
IF COL_LENGTH(N'dbo.COTIZACION', N'TITULO') IS NULL ALTER TABLE [dbo].[COTIZACION] ADD [TITULO] NVARCHAR(200) NULL;
IF COL_LENGTH(N'dbo.COTIZACION', N'ID_CLIENTE') IS NULL ALTER TABLE [dbo].[COTIZACION] ADD [ID_CLIENTE] INT NULL;
IF COL_LENGTH(N'dbo.COTIZACION', N'FORMA_PAGO') IS NULL ALTER TABLE [dbo].[COTIZACION] ADD [FORMA_PAGO] NVARCHAR(10) NULL;
IF COL_LENGTH(N'dbo.COTIZACION', N'DETALLE') IS NULL ALTER TABLE [dbo].[COTIZACION] ADD [DETALLE] NVARCHAR(1000) NULL;
IF COL_LENGTH(N'dbo.COTIZACION', N'ESTADO') IS NULL ALTER TABLE [dbo].[COTIZACION] ADD [ESTADO] NVARCHAR(30) NULL;
IF COL_LENGTH(N'dbo.COTIZACION', N'FECHA_APROBACION') IS NULL ALTER TABLE [dbo].[COTIZACION] ADD [FECHA_APROBACION] DATETIME2 NULL;
IF COL_LENGTH(N'dbo.COTIZACION', N'FECHA_VIGENCIA') IS NULL ALTER TABLE [dbo].[COTIZACION] ADD [FECHA_VIGENCIA] DATETIME2 NULL;
IF COL_LENGTH(N'dbo.COTIZACION', N'CODFACTURA') IS NULL ALTER TABLE [dbo].[COTIZACION] ADD [CODFACTURA] INT NULL;
IF COL_LENGTH(N'dbo.COTIZACION_DETALLE', N'DETALLE') IS NULL ALTER TABLE [dbo].[COTIZACION_DETALLE] ADD [DETALLE] NVARCHAR(500) NULL;
IF COL_LENGTH(N'dbo.COTIZACION_DETALLE', N'DESCUENTO') IS NULL ALTER TABLE [dbo].[COTIZACION_DETALLE] ADD [DESCUENTO] DECIMAL(18,2) NOT NULL CONSTRAINT [DF_COTIZACION_DETALLE_DESCUENTO] DEFAULT (0);
IF COL_LENGTH(N'dbo.COTIZACION_DETALLE', N'TARIFA_IVA') IS NULL ALTER TABLE [dbo].[COTIZACION_DETALLE] ADD [TARIFA_IVA] INT NOT NULL CONSTRAINT [DF_COTIZACION_DETALLE_TARIFA_IVA] DEFAULT (0);
