IF OBJECT_ID('dbo.ESIGN_FIRMA_CONFIGURACION', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ESIGN_FIRMA_CONFIGURACION
    (
        ID_CONFIGURACION INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ESIGN_FIRMA_CONFIGURACION PRIMARY KEY,
        ID_USUARIO INT NOT NULL,
        PATH_CERTIFICADO NVARCHAR(250) NOT NULL,
        CLAVE_CERTIFICADO NVARCHAR(MAX) NOT NULL,
        FECHA_ACTUALIZACION DATETIME2 NOT NULL CONSTRAINT DF_ESIGN_FIRMA_CONFIGURACION_FECHA DEFAULT SYSUTCDATETIME()
    );
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ESIGN_FIRMA_CONFIGURACION_USUARIO' AND object_id = OBJECT_ID(N'dbo.ESIGN_FIRMA_CONFIGURACION'))
    CREATE UNIQUE INDEX UX_ESIGN_FIRMA_CONFIGURACION_USUARIO ON dbo.ESIGN_FIRMA_CONFIGURACION (ID_USUARIO);
