SET XACT_ABORT ON;
BEGIN TRANSACTION;

ALTER TABLE dbo.USU_SOLICITUD_FIRMA
    ALTER COLUMN SOL_ID_USUARIO_CLIENTE INT NULL;

IF OBJECT_ID(N'dbo.ESIGN_SOLICITUD_BORRADOR', N'U') IS NOT NULL
    ALTER TABLE dbo.ESIGN_SOLICITUD_BORRADOR
        ALTER COLUMN BOR_ID_USUARIO INT NULL;

COMMIT TRANSACTION;
