IF COL_LENGTH('dbo.VENDEDOR_BACKOFFICE', 'BancoPago') IS NULL
    ALTER TABLE dbo.VENDEDOR_BACKOFFICE ADD BancoPago NVARCHAR(120) NULL;
IF COL_LENGTH('dbo.VENDEDOR_BACKOFFICE', 'TipoCuentaPago') IS NULL
    ALTER TABLE dbo.VENDEDOR_BACKOFFICE ADD TipoCuentaPago NVARCHAR(20) NULL;
IF COL_LENGTH('dbo.VENDEDOR_BACKOFFICE', 'NumeroCuentaPago') IS NULL
    ALTER TABLE dbo.VENDEDOR_BACKOFFICE ADD NumeroCuentaPago NVARCHAR(30) NULL;
IF COL_LENGTH('dbo.VENDEDOR_BACKOFFICE', 'TitularCuentaPago') IS NULL
    ALTER TABLE dbo.VENDEDOR_BACKOFFICE ADD TitularCuentaPago NVARCHAR(120) NULL;
