IF OBJECT_ID('dbo.ALIADO_LIQUIDACION_FACTURA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ALIADO_LIQUIDACION_FACTURA
    (
        IdRevision INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        IdLiquidacion INT NOT NULL,
        ArchivoUrl NVARCHAR(300) NOT NULL,
        NombreArchivo NVARCHAR(180) NOT NULL,
        TipoArchivo NVARCHAR(80) NOT NULL,
        Estado NVARCHAR(30) NOT NULL,
        Observacion NVARCHAR(500) NULL,
        FechaRegistro DATETIME2 NOT NULL,
        IdUsuarioRegistro INT NOT NULL,
        FechaRevision DATETIME2 NULL,
        IdUsuarioRevision INT NULL
    );
END
IF OBJECT_ID('dbo.ALIADO_LIQUIDACION_NOTIFICACION', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ALIADO_LIQUIDACION_NOTIFICACION
    (
        IdNotificacion INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        IdLiquidacion INT NOT NULL,
        Tipo NVARCHAR(40) NOT NULL,
        FechaEnvio DATETIME2 NOT NULL
    );
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ALIADO_LIQUIDACION_FACTURA_LIQ' AND object_id = OBJECT_ID('dbo.ALIADO_LIQUIDACION_FACTURA'))
    CREATE INDEX IX_ALIADO_LIQUIDACION_FACTURA_LIQ ON dbo.ALIADO_LIQUIDACION_FACTURA(IdLiquidacion, IdRevision DESC);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_ALIADO_LIQUIDACION_NOTIFICACION' AND object_id = OBJECT_ID('dbo.ALIADO_LIQUIDACION_NOTIFICACION'))
    CREATE UNIQUE INDEX UX_ALIADO_LIQUIDACION_NOTIFICACION ON dbo.ALIADO_LIQUIDACION_NOTIFICACION(IdLiquidacion, Tipo);
