SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.ALIADO_LIQUIDACION', 'PagoConfirmadoCliente') IS NULL
    ALTER TABLE dbo.ALIADO_LIQUIDACION ADD PagoConfirmadoCliente BIT NOT NULL CONSTRAINT DF_ALIADO_LIQUIDACION_PAGO_CONFIRMADO_CLIENTE DEFAULT (0);

IF COL_LENGTH('dbo.ALIADO_LIQUIDACION', 'FechaConfirmacionCliente') IS NULL
    ALTER TABLE dbo.ALIADO_LIQUIDACION ADD FechaConfirmacionCliente DATETIME2 NULL;

IF COL_LENGTH('dbo.ALIADO_LIQUIDACION', 'IdUsuarioConfirmacionCliente') IS NULL
    ALTER TABLE dbo.ALIADO_LIQUIDACION ADD IdUsuarioConfirmacionCliente INT NULL;

COMMIT TRANSACTION;
