IF OBJECT_ID(N'dbo.VENDEDOR_COMISION', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.VENDEDOR_COMISION
    (
        IdComision INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_VENDEDOR_COMISION PRIMARY KEY,
        IdVendedor INT NOT NULL,
        IdFactura INT NOT NULL,
        IdCliente INT NULL,A
        TipoComision NVARCHAR(40) NOT NULL,
        BaseComisionable DECIMAL(18,2) NOT NULL,
        Porcentaje DECIMAL(9,4) NOT NULL,
        Valor DECIMAL(18,2) NOT NULL,
        Periodo NVARCHAR(7) NOT NULL,
        Estado NVARCHAR(20) NOT NULL CONSTRAINT DF_VENDEDOR_COMISION_ESTADO DEFAULT(N'Pendiente'),
        FechaGeneracion DATETIME2 NOT NULL CONSTRAINT DF_VENDEDOR_COMISION_FECHA DEFAULT(SYSDATETIME()),
        FechaPago DATETIME2 NULL,
        IdUsuarioPago INT NULL
    );
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_VENDEDOR_COMISION_FACTURA_TIPO' AND object_id = OBJECT_ID(N'dbo.VENDEDOR_COMISION'))
    CREATE UNIQUE INDEX UX_VENDEDOR_COMISION_FACTURA_TIPO ON dbo.VENDEDOR_COMISION(IdVendedor, IdFactura, TipoComision);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_VENDEDOR_COMISION_ESTADO' AND object_id = OBJECT_ID(N'dbo.VENDEDOR_COMISION'))
    CREATE INDEX IX_VENDEDOR_COMISION_ESTADO ON dbo.VENDEDOR_COMISION(IdVendedor, Estado, FechaGeneracion DESC);
