SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.GUIAREMISION', 'codEmisor') IS NULL
    ALTER TABLE dbo.GUIAREMISION ADD codEmisor INT NULL;

ALTER TABLE dbo.GUIAREMISION ALTER COLUMN idUsuario INT NULL;
ALTER TABLE dbo.NOTASDEBITO ALTER COLUMN usuario INT NULL;

COMMIT TRANSACTION;
